config/routes.rb
Rails.application.routes.draw do

  get "log_out" => "sessions#destroy", as: "log_out"
  get "log_in" => "sessions#new", as: "log_in"
  get "sign_up" => "users#new", as: "sign_up"

  root 'welcome#index'

  resources :users
  resources :sessions

  match "welcome/get_login_num" => "welcome#get_login_num", via: [:get]

end

app/models/user.rb
class User < ActiveRecord::Base
	attr_accessor :password

	before_save :encrypt_password

	validates_presence_of :password, on: :create
	validates_confirmation_of :password
	validates_presence_of :nickname
	validates_uniqueness_of :nickname

	def self.authenticate(nickname, password)
		user = find_by_nickname(nickname)
		if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
			user
		else
			nil
		end
	end

	def encrypt_password
		if password.present?
			self.password_salt = BCrypt::Engine.generate_salt
			self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
		end
	end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
	protect_from_forgery with: :exception
	helper_method :current_user

	# before_action :current_user, :auth_log_in

	private

	def current_user
	  	@current_user ||= session[:user_id] && User.find(session[:user_id])
	end

	def auth_log_in
	  	unless current_user
	  		redirect_to log_in_path, error: "请先登陆"
	  	end
	end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  	
  end

  def create
  	user = User.authenticate(params[:nickname], params[:password])
  	if user
  		session[:user_id] = user.id
             session[:login_time] = Time.now

             user_login_info = Oj.load(REDIS.get("user_id_#{user.id}"))

            session[:login_num] = user_login_info[:login_num].to_i + 1
            session[:login_dura] = user_login_info[:login_dura]

            user.is_login = true
            user.save

  		redirect_to root_path, notice: "欢迎回来"
  	else
  		flash.now.alert = "无效的用户名或者密码"
  		render "new"
  	end
  end

  def destroy
    now = Time.now
    login_time = session[:login_time].split(" ")
    date = login_time[0].split("-")
    time = login_time[1].split(":")

    pre_time = Time.new(date[0],date[1],date[2],time[0],time[1],time[2])
    login_dura = ((now - pre_time) / 60).round + session[:login_dura]

    uid = session[:user_id]
    login_info = {login_num: session[:login_num], login_dura: login_dura}

    REDIS.set("user_id_#{uid}",Oj.dump(login_info))

    user = User.find(uid)
    user.is_login = false
    user.save

    session[:login_time] = nil
    session[:user_id] = nil
    session[:login_num] = nil
    session[:login_dura] = nil
    flash[:notice] = "下次再见"
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  	@user = User.new
  end

  def create
  	@user = User.new(user_params)
  	if @user.save
          session[:user_id] = @user.id
          session[:login_time] = Time.now
          session[:login_num] = 1
          session[:login_dura] = 0

          hash = {login_num: 1,login_dura: 0}
          REDIS.set("user_id_#{current_user.id}",Oj.dump(hash))

          flash[:notice] = "注册成功！"
  	    redirect_to root_path
  	else	
  		render "new"
  	end
  end

  private

  def user_params
  	params.require(:user).permit(:password, :nickname, :password_confirmation)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
	def index
		@login_count = User.where(is_login: true).count

		now = Time.now

		if current_user
			login_time = session[:login_time].split(" ")

			# puts login_time.inspect
			date = login_time[0].split("-")
			time = login_time[1].split(":")

			# puts "ddddsssseee"
			# puts session[:login_dura]

			pre_time = Time.new(date[0],date[1],date[2],time[0],time[1],time[2])
			# puts pre_time
			@time = ((now - pre_time) / 60).round + session[:login_dura]
			@count = session[:login_num]
		else
			if session[:login_time]
				login_time= session[:login_time].split(" ")
				date = login_time[0].split("-")
				time = login_time[1].split(":")

				pre_time = Time.new(date[0],date[1],date[2],time[0],time[1],time[2])
				# puts pre_time

				@time = ((now - pre_time) / 60).round
			else
				session[:login_time] = now
				@time = 0
			end

		end
	end

	def get_login_num
		login_count = User.where(is_login: true).count
		#not_login_count 不知道怎么区分未登录用户，所以没有做
		not_login_count = 0

		render json: {login_count: login_count, not_login_count: not_login_count}
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>
    <div id="navbar" class="collapse navbar-collapse">
      <ul class="nav navbar-nav navbar-right">
        <% if current_user %>
          <li><p>欢迎，<%= current_user.nickname %></p></li>
          <li><%= link_to "注销", log_out_path %></li>
        <% else %>
          <li><%= link_to "登陆", log_in_path %></li>
          <li><%= link_to "注册", sign_up_path %></li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_message.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SampleWeb</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<%= render 'layouts/header' %>
	<div class="container">
		<div class="row">
			<%= yield %>
		</div>
      </div>
</body>
</html>

app/views/users/new.html.erb
<% if @user.errors.any? %>
	<%= content_tag :div, class: "alert alert-danger" do %>
		<button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
		<ul>
	  <% @user.errors.full_messages.each do |msg| %>
	  	<li><%= msg %></li>
	  <% end %>
	  </ul>
	<% end %>
<% end %>

<%= form_for @user, html: {class: "form-signin", role: "form"} do |f| %>
	<%= content_tag :h2, "注册", class: "form-signin-heading" %>
	<%= f.text_field :nickname, class: "form-control", placeholder: "姓名" %>
	<%= f.password_field :password, class: "form-control", placeholder: "密码" %>
	<%= f.password_field :password_confirmation, class: "form-control", placeholder: "再输一次" %>
	<%= f.submit :确定, class: "btn btn-lg btn-primary btn-block" %>
<% end %>

app/views/welcome/index.html.erb
<%= render 'layouts/message' %>

<%if current_user%>
	<p><%= @current_user.nickname %>谢谢你登录了我们网站！你已经登录了 <%= @count %> 次了，总共登录时间是 <%= @time %> 分钟了。</p>
<% else %>
	<p>你好，陌生人！你没有登录，或者你还没有注册，但是你已经浏览这个页面 <%= @time %> 分钟了。</p>
<% end %>

<p>现在总共有 <%= @login_count %> 个注册用户在查看这个网站，有 {m} 个陌生人在查看这个网站</p>